import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "1rem 2rem",
          backgroundColor: "#ff6f00", // لون برتقالي مشابه لنون
          color: "white",
          fontWeight: "bold",
          fontSize: "1.25rem",
          fontFamily: "var(--font-geist-sans)",
        }}>
          <div style={{ cursor: "pointer" }}>
            {/* شعار نون */}
            Noon
          </div>
          <nav style={{ display: "flex", gap: "1.5rem" }}>
            <a href="#" style={{ color: "white", textDecoration: "none" }}>Home</a>
            <a href="#" style={{ color: "white", textDecoration: "none" }}>Categories</a>
            <a href="#" style={{ color: "white", textDecoration: "none" }}>Deals</a>
            <a href="#" style={{ color: "white", textDecoration: "none" }}>Cart</a>
            <a href="#" style={{ color: "white", textDecoration: "none" }}>Login</a>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
